
#' Generate an UpSet plot of reproducible and replicate peaks
#'
#' This function creates an UpSet plot showing the intersection between a set of reproducible peaks
#' and multiple replicate peak sets. It pads replicate peak lists with dummy values to ensure that
#' the set size bars in the UpSet plot accurately reflect the total number of peaks in each replicate.
#' The final plot includes only reproducible peaks in the intersection matrix but uses the accurate set size bars.
#'
#' @param reproduciblePeaksPath Character string. File path to a BED file of reproducible peaks.
#' @param replicatePeakPaths Character vector. File paths to BED files containing peak calls for each replicate.
#' @param replicateLabels Character vector. Display labels for the replicate peak sets (must match order of paths).
#'
#' @return A list object generated by \code{UpSetR::upset()}, representing the UpSet plot.
#' @examples
#' makeUpSetPlot(
#'   reproduciblePeaksPath = "Reproducible_MTBP.bed",
#'   replicatePeakPaths = c("rep1.bed", "rep2.bed", "rep3.bed"),
#'   replicateLabels = c("Rep 1", "Rep 2", "Rep 3")
#' )
#' @import UpSetR
#' @export
makeUpSetPlot <- function(
    reproduciblePeaksPath = "../MakeReproduciblePeaks/MTBP_Peaks_Reproducible_6.narrowPeak",
    replicatePeakPaths = paste0("../01_Asynchronous_HCT116/results/macs2_normalPeaks/", asynchronousPeakFiles[grep("MTBP", asynchronousPeakFiles)]),
    replicateLabels = c("1:1000 1", "1:1000 2", "1:1000 3", "1:250 1", "1:250 2", "1:250 3")
) {
  # Read reproducible peaks into a GenomicRanges object
  reproduciblePeaks <- readBed(reproduciblePeaksPath)

  # Read replicate peak files into a named list of GenomicRanges
  replicatePeaksList <- lapply(replicatePeakPaths, readBed) %>%
    setNames(., replicateLabels)

  # Function to extract overlapping peaks between reproducible peaks and each replicate
  getOverlappingPeaks <- function(queryPeaks, peakList) {
    lapply(peakList, function(gr) {
      queryPeaks[queryPeaks %over% gr] %>%
        { paste0(seqnames(.), ":", start(.), "-", end(.)) }
    })
  }

  # Generate named list of reproducible peaks overlapping each replicate
  overlappingPeaks <- getOverlappingPeaks(reproduciblePeaks, replicatePeaksList) %>%
    setNames(., replicateLabels)

  # Function to pad replicate peak lists with dummy peaks so UpSetR plots total set sizes correctly
  padWithDummyPeaks <- function(sampleLabel, overlapList, allPeaksList) {
    totalPeaks <- length(allPeaksList[[sampleLabel]])
    overlapping <- length(overlapList[[sampleLabel]])
    nMissing <- totalPeaks - overlapping
    dummyPeaks <- paste0(sampleLabel, seq_len(nMissing))
    c(overlapList[[sampleLabel]], dummyPeaks)
  }

  # Pad overlapping peaks with dummy values to match full peak counts per replicate
  paddedPeaks <- lapply(names(overlappingPeaks), padWithDummyPeaks, overlappingPeaks, replicatePeaksList) %>%
    set_names(., names(overlappingPeaks))

  # Create list with only reproducible peaks for UpSetR input (for overlap-only plot)
  overlapOnlyList <- list(paste0(seqnames(reproduciblePeaks), ":", start(reproduciblePeaks), "-", end(reproduciblePeaks))) %>%
    append(overlappingPeaks, .)
  names(overlapOnlyList)[length(overlapOnlyList)] <- "Reproducible Peaks"

  # Create list with dummy-padded peak overlaps (for full peak count plot)
  paddedOverlapList <- list(paste0(seqnames(reproduciblePeaks), ":", start(reproduciblePeaks), "-", end(reproduciblePeaks))) %>%
    append(paddedPeaks, .)
  names(paddedOverlapList)[length(paddedOverlapList)] <- "Reproducible Peaks"

  # Convert both lists into UpSetR-compatible data frames
  overlapOnly_df <- UpSetR::fromList(overlapOnlyList)
  paddedOverlap_df <- UpSetR::fromList(paddedOverlapList)

  # Create UpSetR plot showing only reproducible peak overlaps
  overlapOnlyPlot <- UpSetR::upset(
    overlapOnly_df,
    sets = c(replicateLabels, "Reproducible Peaks"),
    keep.order = TRUE,
    order.by = "freq",
    number.angles = 90,
    nintersects = 20
  )

  # Create UpSetR plot including dummy peaks (for accurate set sizes)
  fullSetSizePlot <- UpSetR::upset(
    paddedOverlap_df,
    group.by = "degree",
    order.by = "freq",
    sets = c(replicateLabels, "Reproducible Peaks"),
    keep.order = TRUE,
    number.angles = 90,
    nintersects = 20
  )

  # Replace set size bars in overlap-only plot with accurate ones from the full set size plot
  overlapOnlyPlot$Sizes <- fullSetSizePlot$Sizes

  # Return the final plot
  overlapOnlyPlot
}
