
#' Plot Median Log2 Fold Change by Replication Timing Fraction
#'
#' Creates a line plot of the median log2 fold change across S-phase fractions (S1 to S16).
#' This is useful for visualizing how signal enrichment or depletion changes across the replication timing program.
#'
#' @param df A `data.frame` with columns `S.fraction` (factor) and `Log2FC` (numeric),
#'   typically generated by `summarize_log2fc_by_rt_fraction()`.
#' @param title Optional plot title to display.
#'
#' @return A `ggplot` object.
#'
#' @import ggplot2
#' @import magrittr
#' @export
plot_log2fc_median_by_fraction <- function(df, title = NULL) {
  df_median <- aggregate(Log2FC ~ S.fraction, df, FUN = function(x) median(x[is.finite(x)]))
  df_median$S.fraction.numeric <- gsub("S", "", df_median$S.fraction) %>% as.numeric()

  ggplot(df_median, aes(x = S.fraction.numeric, y = Log2FC)) +
    geom_line() +
    geom_point(size = 1) +
    theme_bw() +
    sansam_theme() +
    xlab("Rep. timing") +
    ylab("Log2(Sig/Bkg)") +
    ggtitle(title)
}
